name: app_gastos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # Dependencias

  provider: ^4.3.3

  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: 0.16.0+1

  google_sign_in: ^4.5.9
  
  charts_flutter: ^0.9.0
  font_awesome_flutter: ^8.11.0

  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
